spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resume_king?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.resumebuilder.entity
  configuration:
    map-underscore-to-camel-case: true

aliyun:
  oss:
    
