// import { Component } from '../store/resume'
//
// export const createCreativeTemplate = (): Component[] => {
//   return[
//     {
//       "id": "header-name",
//       "type": "text-title",
//       "x": 40,
//       "y": 40,
//       "width": 300,
//       "height": 50,
//       "content": "李明",
//       "fontSize": 38,
//       "fontFamily": "Microsoft YaHei",
//       "color": "#2c3e50",
//       "textAlign": "left",
//       "lineHeight": 1.2
//     },
//     {
//       "id": "header-job-title",
//       "type": "text-basic",
//       "x": 40,
//       "y": 95,
//       "width": 300,
//       "height": 30,
//       "content": "资深前端开发工程师",
//       "fontSize": 20,
//       "fontFamily": "Microsoft YaHei",
//       "color": "#34495e",
//       "textAlign": "left",
//       "lineHeight": 1.5
//     },
//     {
//       "id": "header-contact",
//       "type": "text-basic",
//       "x": 40,
//       "y": 135,
//       "width": 515,
//       "height": 30,
//       "content": "📱 139-1234-5678 | 📧 liming@example.com | 📍 深圳市南山区 | GitHub: github.com/liming",
//       "fontSize": 14,
//       "fontFamily": "Microsoft YaHei",
//       "color": "#7f8c8d",
//       "textAlign": "left",
//       "lineHeight": 1.5
//     },
//     {
//       "id": "profile-image",
//       "type": "image",
//       "x": 442,
//       "y": 21,
//       "width": 100,
//       "height": 100,
//       "imageUrl": "https://web-oss-learn.oss-cn-beijing.aliyuncs.com/resume/images/d95cc750-bc28-4f9b-b480-6c8dc0622456.png",
//       "aspectRatio": 1,
//       "fontFamily": "Microsoft YaHei",
//       "fontSize": 16,
//       "color": "#000000"
//     },
//     {
//       "id": "divider-1",
//       "type": "divider-solid",
//       "x": 40,
//       "y": 176,
//       "width": 515,
//       "height": 20,
//       "color": "#3498db",
//       "padding": 10,
//       "thickness": 1,
//       "fontFamily": "Microsoft YaHei",
//       "fontSize": 16
//     },
//     {
//       "id": "summary-title",
//       "type": "text-title",
//       "x": 40,
//       "y": 188,
//       "width": 200,
//       "height": 30,
//       "content": "个人总结",
//       "fontSize": 22,
//       "fontFamily": "Microsoft YaHei",
//       "color": "#2c3e50",
//       "textAlign": "left",
//       "lineHeight": 1.5
//     },
//     {
//       "id": "summary-content",
//       "type": "text-basic",
//       "x": 36,
//       "y": 223,
//       "width": 515,
//       "height": 80,
//       "content": "拥有5年以上前端开发经验，精通Vue.js、React等主流前端框架，熟悉Node.js后端开发。具备扎实的计算机基础和良好的代码规范，能够独立承担项目开发，并具备团队协作和沟通能力。致力于通过技术提升用户体验和产品价值。",
//       "fontSize": 14,
//       "fontFamily": "Microsoft YaHei",
//       "color": "#34495e",
//       "textAlign": "left",
//       "lineHeight": 1.6
//     },
//     {
//       "id": "divider-2",
//       "type": "divider-solid",
//       "x": 40,
//       "y": 320,
//       "width": 515,
//       "height": 20,
//       "color": "#3498db",
//       "padding": 10,
//       "thickness": 1,
//       "fontFamily": "Microsoft YaHei",
//       "fontSize": 16
//     },
//     {
//       "id": "skills-title",
//       "type": "text-title",
//       "x": 40,
//       "y": 333,
//       "width": 200,
//       "height": 30,
//       "content": "专业技能",
//       "fontSize": 22,
//       "fontFamily": "Microsoft YaHei",
//       "color": "#2c3e50",
//       "textAlign": "left",
//       "lineHeight": 1.5
//     },
//     {
//       "id": "skills-content",
//       "type": "text-basic",
//       "x": 36,
//       "y": 369,
//       "width": 515,
//       "height": 100,
//       "content": "• 前端框架：Vue.js (Vuex, Vue Router), React (Redux, React Router), Angular\n• 编程语言：JavaScript (ES6+), TypeScript, HTML5, CSS3 (Sass/Less)\n• 后端技术：Node.js (Express, Koa), Python (Django, Flask)\n• 数据库：MySQL, MongoDB, Redis\n• 工具：Webpack, Babel, Git, Docker, Jenkins",
//       "fontSize": 14,
//       "fontFamily": "Microsoft YaHei",
//       "color": "#34495e",
//       "textAlign": "left",
//       "lineHeight": 1.6
//     },
//     {
//       "id": "divider-3",
//       "type": "divider-solid",
//       "x": 40,
//       "y": 489,
//       "width": 515,
//       "height": 20,
//       "color": "#3498db",
//       "padding": 10,
//       "thickness": 1,
//       "fontFamily": "Microsoft YaHei",
//       "fontSize": 16
//     },
//     {
//       "id": "experience-title",
//       "type": "text-title",
//       "x": 40,
//       "y": 502,
//       "width": 200,
//       "height": 30,
//       "content": "工作经历",
//       "fontSize": 22,
//       "fontFamily": "Microsoft YaHei",
//       "color": "#2c3e50",
//       "textAlign": "left",
//       "lineHeight": 1.5
//     },
//     {
//       "id": "experience-1-company",
//       "type": "text-basic",
//       "x": 37,
//       "y": 538,
//       "width": 515,
//       "height": 30,
//       "content": "**腾讯科技（深圳）有限公司** | 高级前端开发工程师 | 2022.03 - 至今",
//       "fontSize": 16,
//       "fontFamily": "Microsoft YaHei",
//       "color": "#34495e",
//       "textAlign": "left",
//       "lineHeight": 1.5,
//       "fontWeight": 700
//     },
//     {
//       "id": "experience-1-desc",
//       "type": "text-basic",
//       "x": 40,
//       "y": 571,
//       "width": 515,
//       "height": 100,
//       "content": "• 负责微信小程序核心业务模块开发与性能优化，将首屏加载时间缩短30%\n• 参与设计并实现组件库，提高开发效率50%\n• 引入自动化测试流程，保障代码质量和稳定性\n• 带领3人团队完成多个大型项目，按时高质量交付",
//       "fontSize": 14,
//       "fontFamily": "Microsoft YaHei",
//       "color": "#34495e",
//       "textAlign": "left",
//       "lineHeight": 1.6
//     },
//     {
//       "id": "divider-4",
//       "type": "divider-solid",
//       "x": 40,
//       "y": 667,
//       "width": 515,
//       "height": 20,
//       "color": "#3498db",
//       "padding": 10,
//       "thickness": 1,
//       "fontFamily": "Microsoft YaHei",
//       "fontSize": 16
//     },
//     {
//       "id": "education-title",
//       "type": "text-title",
//       "x": 34,
//       "y": 683,
//       "width": 200,
//       "height": 30,
//       "content": "教育背景",
//       "fontSize": 22,
//       "fontFamily": "Microsoft YaHei",
//       "color": "#2c3e50",
//       "textAlign": "left",
//       "lineHeight": 1.5
//     },
//     {
//       "id": "education-content",
//       "type": "text-basic",
//       "x": 35,
//       "y": 730,
//       "width": 515,
//       "height": 73,
//       "content": "2015.09 - 2019.06 | 华中科技大学 | 软件工程 | 本科\n• 主修课程：数据结构、算法、操作系统、计算机网络、软件工程\n• 荣获校级优秀毕业生、一等奖学金",
//       "fontSize": 14,
//       "fontFamily": "Microsoft YaHei",
//       "color": "#34495e",
//       "textAlign": "left",
//       "lineHeight": 1.6
//     }
//   ]
// }