import { Component } from '../store/resume'

export const createModernTemplate = (): Component[] => {
  return [
    {
      "id": "name-1749787157800",
      "type": "text-title",
      "x": 40,
      "y": 40,
      "width": 300,
      "height": 50,
      "content": "李四",
      "fontSize": 32,
      "fontFamily": "Microsoft YaHei",
      "color": "#2c3e50",
      "textAlign": "left",
      "lineHeight": 1.2
    },
    {
      "id": "title-1749787157800",
      "type": "text-basic",
      "x": 40,
      "y": 95,
      "width": 300,
      "height": 30,
      "content": "全栈开发工程师",
      "fontSize": 18,
      "fontFamily": "Microsoft YaHei",
      "color": "#34495e",
      "textAlign": "left",
      "lineHeight": 1.5
    },
    {
      "id": "contact-1749787157800",
      "type": "text-basic",
      "x": 40,
      "y": 135,
      "width": 515,
      "height": 30,
      "content": "📱 139-xxxx-xxxx | 📧 lisi@email.com | 📍 上海市浦东新区",
      "fontSize": 14,
      "fontFamily": "Microsoft YaHei",
      "color": "#7f8c8d",
      "textAlign": "left",
      "lineHeight": 1.5
    },
    {
      "id": "divider-1749787157800",
      "type": "divider-solid",
      "x": 40,
      "y": 176,
      "width": 515,
      "height": 20,
      "color": "#3498db",
      "padding": 10,
      "thickness": 1,
      "fontFamily": "Microsoft YaHei",
      "fontSize": 16
    },
    {
      "id": "skills-title-1749787157800",
      "type": "text-title",
      "x": 40,
      "y": 188,
      "width": 200,
      "height": 30,
      "content": "专业技能",
      "fontSize": 20,
      "fontFamily": "Microsoft YaHei",
      "color": "#2c3e50",
      "textAlign": "left",
      "lineHeight": 1.5
    },
    {
      "id": "skills-content-1749787157800",
      "type": "text-basic",
      "x": 36,
      "y": 223,
      "width": 515,
      "height": 80,
      "content": "• 前端：Vue.js、React、TypeScript、Webpack\n• 后端：Node.js、Python、Java、Spring Boot\n• 数据库：MySQL、MongoDB、Redis\n• 其他：Docker、Git、CI/CD、微服务架构",
      "fontSize": 14,
      "fontFamily": "Microsoft YaHei",
      "color": "#34495e",
      "textAlign": "left",
      "lineHeight": 1.6
    },
    {
      "id": "work-title-1749787157800",
      "type": "text-title",
      "x": 40,
      "y": 333,
      "width": 200,
      "height": 30,
      "content": "工作经历",
      "fontSize": 20,
      "fontFamily": "Microsoft YaHei",
      "color": "#2c3e50",
      "textAlign": "left",
      "lineHeight": 1.5
    },
    {
      "id": "work-company-1749787157800",
      "type": "text-basic",
      "x": 37,
      "y": 369,
      "width": 515,
      "height": 30,
      "content": "科技互联网公司 | 高级全栈工程师 | 2021.03-至今",
      "fontSize": 16,
      "fontFamily": "Microsoft YaHei",
      "color": "#34495e",
      "textAlign": "left",
      "lineHeight": 1.5
    },
    {
      "id": "work-desc-1749787157800",
      "type": "text-basic",
      "x": 40,
      "y": 402,
      "width": 515,
      "height": 80,
      "content": "• 主导公司核心业务系统的架构设计和开发\n• 优化系统性能，将页面加载时间减少50%\n• 设计并实现微服务架构，提升系统可扩展性\n• 带领5人团队完成多个重要项目交付",
      "fontSize": 14,
      "fontFamily": "Microsoft YaHei",
      "color": "#34495e",
      "textAlign": "left",
      "lineHeight": 1.6,
      "fontWeight": 400
    },
    {
      "id": "1749787163254",
      "type": "image",
      "x": 442,
      "y": 21,
      "width": 94,
      "height": 94,
      "fontSize": 16,
      "fontFamily": "Microsoft YaHei",
      "color": "#000000",
      "isResizing": false,
      "imageUrl": "https://web-oss-learn.oss-cn-beijing.aliyuncs.com/resume/images/d95cc750-bc28-4f9b-b480-6c8dc0622456.png",
      "aspectRatio": 1,
      "originalWidth": 97,
      "originalHeight": 97
    },
    {
      "id": "1749790653772",
      "type": "divider-solid",
      "x": 40,
      "y": 320,
      "width": 515,
      "height": 20,
      "color": "#3498db",
      "padding": 10,
      "thickness": 1,
      "fontFamily": "Microsoft YaHei",
      "fontSize": 16,
      "isResizing": false
    },
    {
      "id": "1749790855674",
      "type": "divider-solid",
      "x": 37,
      "y": 628,
      "width": 515,
      "height": 20,
      "color": "#3498db",
      "padding": 10,
      "thickness": 1,
      "fontFamily": "Microsoft YaHei",
      "fontSize": 16,
      "isResizing": false
    },
    {
      "id": "1749790920031",
      "type": "text-basic",
      "x": 39.8203125,
      "y": 550,
      "width": 447,
      "height": 73,
      "content": " •负责核心交易系统的高并发、低延迟优化，吞吐量提升50%\n •设计并实现分布式缓存服务，响应时间缩短30%\n •带领3人团队完成新功能模块开发，按时交付",
      "fontSize": 14,
      "fontFamily": "Microsoft YaHei",
      "color": "#34495e",
      "fontWeight": 400,
      "lineHeight": 1.6,
      "textAlign": "left",
      "isResizing": false
    },
    {
      "id": "1749791245964",
      "type": "text-basic",
      "x": 37,
      "y": 509,
      "width": 433,
      "height": 30,
      "content": "百度公司          | 软件工程师       | 2016.07-2019.06",
      "fontSize": 16,
      "fontFamily": "Microsoft YaHei",
      "color": "#34495e",
      "fontWeight": 400,
      "lineHeight": 1.5,
      "textAlign": "left",
      "isResizing": false
    },
    {
      "id": "1749791425087",
      "type": "text-basic",
      "x": 40,
      "y": 682,
      "width": 506,
      "height": 128,
      "content": "一位充满激情和创新精神的UI/UX设计师，拥有6年行业经验\n擅长用户研究、原型设计、视觉设计和可用性测试\n致力于为用户提供直观、愉悦的产品体验\n熟练运用Figma、Sketch、Adobe XD等设计工具。",
      "fontSize": 14,
      "fontFamily": "Microsoft YaHei",
      "color": "#34495e",
      "fontWeight": 400,
      "lineHeight": 1.6,
      "textAlign": "left",
      "isResizing": false
    },
    {
      "id": "1749791486971",
      "type": "text-basic",
      "x": 36.8203125,
      "y": 642,
      "width": 100,
      "height": 30,
      "content": "自我评价",
      "fontSize": 20,
      "fontFamily": "Microsoft YaHei",
      "color": "#2c3e50",
      "fontWeight": 400,
      "lineHeight": 1.5,
      "textAlign": "left",
      "isResizing": false
    }
  ]
} 