// import { Component } from '../store/resume'
//
// export const createProfessionalTemplate = (): Component[] => {
//   return [
//     {
//       "id": "header-professional",
//       "type": "text-title",
//       "x": 40,
//       "y": 40,
//       "width": 520,
//       "height": 40,
//       "content": "王五",
//       "fontSize": 36,
//       "fontFamily": "Arial",
//       "color": "#2c3e50",
//       "textAlign": "center",
//       "lineHeight": 1.2
//     },
//     {
//       "id": "subtitle-professional",
//       "type": "text-basic",
//       "x": 40,
//       "y": 85,
//       "width": 520,
//       "height": 25,
//       "content": "资深产品经理",
//       "fontSize": 18,
//       "fontFamily": "Arial",
//       "color": "#34495e",
//       "textAlign": "center",
//       "lineHeight": 1.5
//     },
//     {
//       "id": "contact-professional",
//       "type": "text-basic",
//       "x": 40,
//       "y": 120,
//       "width": 520,
//       "height": 25,
//       "content": "电话: 137-xxxx-xxxx | 邮箱: wangwu@example.com | LinkedIn: linkedin.com/in/wangwu",
//       "fontSize": 12,
//       "fontFamily": "Arial",
//       "color": "#7f8c8d",
//       "textAlign": "center",
//       "lineHeight": 1.5
//     },
//     {
//       "id": "section-divider-1-professional",
//       "type": "divider-solid",
//       "x": 40,
//       "y": 150,
//       "width": 520,
//       "height": 10,
//       "color": "#3498db",
//       "padding": 5,
//       "thickness": 2
//     },
//     {
//       "id": "summary-title-professional",
//       "type": "text-title",
//       "x": 40,
//       "y": 170,
//       "width": 150,
//       "height": 25,
//       "content": "职业概述",
//       "fontSize": 20,
//       "fontFamily": "Arial",
//       "color": "#2c3e50",
//       "textAlign": "left",
//       "lineHeight": 1.5
//     },
//     {
//       "id": "summary-content-professional",
//       "type": "text-basic",
//       "x": 40,
//       "y": 200,
//       "width": 520,
//       "height": 80,
//       "content": "拥有8年互联网产品经验，擅长从0到1搭建产品，精通产品生命周期管理、市场分析、用户研究及数据驱动决策。成功主导多款千万级用户产品的设计与上线。",
//       "fontSize": 14,
//       "fontFamily": "Arial",
//       "color": "#34495e",
//       "textAlign": "left",
//       "lineHeight": 1.6
//     },
//     {
//       "id": "section-divider-2-professional",
//       "type": "divider-solid",
//       "x": 40,
//       "y": 290,
//       "width": 520,
//       "height": 10,
//       "color": "#3498db",
//       "padding": 5,
//       "thickness": 1
//     },
//     {
//       "id": "experience-title-professional",
//       "type": "text-title",
//       "x": 40,
//       "y": 310,
//       "width": 150,
//       "height": 25,
//       "content": "工作经验",
//       "fontSize": 20,
//       "fontFamily": "Arial",
//       "color": "#2c3e50",
//       "textAlign": "left",
//       "lineHeight": 1.5
//     },
//     {
//       "id": "experience-1-company-professional",
//       "type": "text-basic",
//       "x": 40,
//       "y": 340,
//       "width": 520,
//       "height": 20,
//       "content": "某头部互联网公司 | 产品总监 | 2020.01 - 至今",
//       "fontSize": 16,
//       "fontFamily": "Arial",
//       "color": "#34495e",
//       "textAlign": "left",
//       "lineHeight": 1.5,
//       "fontWeight": 700
//     },
//     {
//       "id": "experience-1-desc-professional",
//       "type": "text-basic",
//       "x": 40,
//       "y": 365,
//       "width": 520,
//       "height": 80,
//       "content": "• 负责公司核心产品线规划与落地，实现用户增长30%\n• 组建并管理10人产品团队，建立高效协作流程\n• 推动产品创新，引入AI技术提升用户体验",
//       "fontSize": 14,
//       "fontFamily": "Arial",
//       "color": "#34495e",
//       "textAlign": "left",
//       "lineHeight": 1.6
//     },
//     {
//       "id": "experience-2-company-professional",
//       "type": "text-basic",
//       "x": 40,
//       "y": 455,
//       "width": 520,
//       "height": 20,
//       "content": "某独角兽创业公司 | 高级产品经理 | 2017.03 - 2019.12",
//       "fontSize": 16,
//       "fontFamily": "Arial",
//       "color": "#34495e",
//       "textAlign": "left",
//       "lineHeight": 1.5,
//       "fontWeight": 700
//     },
//     {
//       "id": "experience-2-desc-professional",
//       "type": "text-basic",
//       "x": 40,
//       "y": 480,
//       "width": 520,
//       "height": 80,
//       "content": "• 负责B端SaaS产品从0到1的搭建，完成市场调研、需求分析、原型设计及上线\n• 协调研发、设计、运营团队，确保项目按时交付\n• 通过数据分析优化产品功能，提升用户留存率15%",
//       "fontSize": 14,
//       "fontFamily": "Arial",
//       "color": "#34495e",
//       "textAlign": "left",
//       "lineHeight": 1.6
//     },
//     {
//       "id": "section-divider-3-professional",
//       "type": "divider-solid",
//       "x": 40,
//       "y": 570,
//       "width": 520,
//       "height": 10,
//       "color": "#3498db",
//       "padding": 5,
//       "thickness": 1
//     },
//     {
//       "id": "skills-title-professional",
//       "type": "text-title",
//       "x": 40,
//       "y": 590,
//       "width": 150,
//       "height": 25,
//       "content": "核心技能",
//       "fontSize": 20,
//       "fontFamily": "Arial",
//       "color": "#2c3e50",
//       "textAlign": "left",
//       "lineHeight": 1.5
//     },
//     {
//       "id": "skills-content-professional",
//       "type": "text-basic",
//       "x": 40,
//       "y": 620,
//       "width": 520,
//       "height": 60,
//       "content": "• 产品管理：产品路线图、需求管理、竞品分析、A/B测试\n• 数据分析：SQL、Excel、GA、用户行为分析\n• 设计工具：Axure、Sketch、Figma\n• 敏捷开发：Scrum、Kanban",
//       "fontSize": 14,
//       "fontFamily": "Arial",
//       "color": "#34495e",
//       "textAlign": "left",
//       "lineHeight": 1.6
//     }
//   ]
// }
//
//
